package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "computersikho")
public class Album implements java.io.Serializable {

	private int albumId;
	private String albumName;
	private String albumDescription;
	private boolean albumIsActive;
	private Date startDate;
	private Date endDate;
	private Set<Image> images = new HashSet(0);

	public Album() {
	}

	public Album(int albumId, String albumName, boolean albumIsActive, Date startDate, Date endDate) {
		this.albumId = albumId;
		this.albumName = albumName;
		this.albumIsActive = albumIsActive;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Album(int albumId, String albumName, String albumDescription, boolean albumIsActive, Date startDate,
			Date endDate, Set<Image> images) {
		this.albumId = albumId;
		this.albumName = albumName;
		this.albumDescription = albumDescription;
		this.albumIsActive = albumIsActive;
		this.startDate = startDate;
		this.endDate = endDate;
		this.images = images;
	}

	@Id

	@Column(name = "album_id", unique = true, nullable = false)
	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	@Column(name = "album_name", nullable = false, length = 200)
	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	@Column(name = "album_description", length = 65535)
	public String getAlbumDescription() {
		return this.albumDescription;
	}

	public void setAlbumDescription(String albumDescription) {
		this.albumDescription = albumDescription;
	}

	@Column(name = "album_is_active", nullable = false)
	public boolean isAlbumIsActive() {
		return this.albumIsActive;
	}

	public void setAlbumIsActive(boolean albumIsActive) {
		this.albumIsActive = albumIsActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
