package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClosureReasonMaster generated by hbm2java
 */
@Entity
@Table(name = "closure_reason_master", catalog = "computersikho")
public class ClosureReasonMaster implements java.io.Serializable {

	private int closureReasonId;
	private String closureReasonDesc;
	private Set<Enquiry> enquiries = new HashSet(0);

	public ClosureReasonMaster() {
	}

	public ClosureReasonMaster(int closureReasonId) {
		this.closureReasonId = closureReasonId;
	}

	public ClosureReasonMaster(int closureReasonId, String closureReasonDesc, Set<Enquiry> enquiries) {
		this.closureReasonId = closureReasonId;
		this.closureReasonDesc = closureReasonDesc;
		this.enquiries = enquiries;
	}

	@Id

	@Column(name = "Closure_ReasonID", unique = true, nullable = false)
	public int getClosureReasonId() {
		return this.closureReasonId;
	}

	public void setClosureReasonId(int closureReasonId) {
		this.closureReasonId = closureReasonId;
	}

	@Column(name = "Closure_Reason_Desc", length = 200)
	public String getClosureReasonDesc() {
		return this.closureReasonDesc;
	}

	public void setClosureReasonDesc(String closureReasonDesc) {
		this.closureReasonDesc = closureReasonDesc;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "closureReasonMaster")
	public Set<Enquiry> getEnquiries() {
		return this.enquiries;
	}

	public void setEnquiries(Set<Enquiry> enquiries) {
		this.enquiries = enquiries;
	}

}
