package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "computersikho")
public class Course implements java.io.Serializable {

	private Integer courseId;
	private String courseName;
	private String courseDescription;
	private int courseDuration;
	private int courseFees;
	private String courseSyllabus;
	private String ageGrpType;
	private Boolean courseIsActive;
	private String coverPhoto;
	private Set<Videos> videoses = new HashSet(0);
	private Set<Paymentmaster> paymentmasters = new HashSet(0);
	private Set<Batch> batchs = new HashSet(0);
	private Set<Student> students = new HashSet(0);
	private Set<Enquiry> enquiries = new HashSet(0);
	private Set<Payment> payments = new HashSet(0);

	public Course() {
	}

	public Course(String courseName, String courseDescription, int courseDuration, int courseFees,
			String courseSyllabus, String ageGrpType) {
		this.courseName = courseName;
		this.courseDescription = courseDescription;
		this.courseDuration = courseDuration;
		this.courseFees = courseFees;
		this.courseSyllabus = courseSyllabus;
		this.ageGrpType = ageGrpType;
	}

	public Course(String courseName, String courseDescription, int courseDuration, int courseFees,
			String courseSyllabus, String ageGrpType, Boolean courseIsActive, String coverPhoto, Set<Videos> videoses,
			Set<Paymentmaster> paymentmasters, Set<Batch> batchs, Set<Student> students, Set<Enquiry> enquiries, Set<Payment> payments) {
		this.courseName = courseName;
		this.courseDescription = courseDescription;
		this.courseDuration = courseDuration;
		this.courseFees = courseFees;
		this.courseSyllabus = courseSyllabus;
		this.ageGrpType = ageGrpType;
		this.courseIsActive = courseIsActive;
		this.coverPhoto = coverPhoto;
		this.videoses = videoses;
		this.paymentmasters = paymentmasters;
		this.batchs = batchs;
		this.students = students;
		this.enquiries = enquiries;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_id", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "course_name", nullable = false, length = 200)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "course_description", nullable = false, length = 65535)
	public String getCourseDescription() {
		return this.courseDescription;
	}

	public void setCourseDescription(String courseDescription) {
		this.courseDescription = courseDescription;
	}

	@Column(name = "course_duration", nullable = false)
	public int getCourseDuration() {
		return this.courseDuration;
	}

	public void setCourseDuration(int courseDuration) {
		this.courseDuration = courseDuration;
	}

	@Column(name = "course_fees", nullable = false)
	public int getCourseFees() {
		return this.courseFees;
	}

	public void setCourseFees(int courseFees) {
		this.courseFees = courseFees;
	}

	@Column(name = "course_syllabus", nullable = false, length = 65535)
	public String getCourseSyllabus() {
		return this.courseSyllabus;
	}

	public void setCourseSyllabus(String courseSyllabus) {
		this.courseSyllabus = courseSyllabus;
	}

	@Column(name = "age_grp_type", nullable = false, length = 200)
	public String getAgeGrpType() {
		return this.ageGrpType;
	}

	public void setAgeGrpType(String ageGrpType) {
		this.ageGrpType = ageGrpType;
	}

	@Column(name = "course_is_active")
	public Boolean getCourseIsActive() {
		return this.courseIsActive;
	}

	public void setCourseIsActive(Boolean courseIsActive) {
		this.courseIsActive = courseIsActive;
	}

	@Column(name = "cover_photo", length = 200)
	public String getCoverPhoto() {
		return this.coverPhoto;
	}

	public void setCoverPhoto(String coverPhoto) {
		this.coverPhoto = coverPhoto;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Videos> getVideoses() {
		return this.videoses;
	}

	public void setVideoses(Set<Videos> videoses) {
		this.videoses = videoses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Paymentmaster> getPaymentmasters() {
		return this.paymentmasters;
	}

	public void setPaymentmasters(Set<Paymentmaster> paymentmasters) {
		this.paymentmasters = paymentmasters;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Batch> getBatchs() {
		return this.batchs;
	}

	public void setBatchs(Set<Batch> batchs) {
		this.batchs = batchs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Enquiry> getEnquiries() {
		return this.enquiries;
	}

	public void setEnquiries(Set<Enquiry> enquiries) {
		this.enquiries = enquiries;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
