package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Followup generated by hbm2java
 */
@Entity
@Table(name = "followup", catalog = "computersikho")
public class Followup implements java.io.Serializable {

	private int followupId;
	private int staff;
	private int enquiry;
	private String followupMsg;
	private boolean isActive;

	public Followup() {
	}

	public Followup(int followupId, int enquiry, boolean isActive) {
		this.followupId = followupId;
		this.enquiry = enquiry;
		this.isActive = isActive;
	}

	public Followup(int followupId, int staff, int enquiry, String followupMsg, boolean isActive) {
		this.followupId = followupId;
		this.staff = staff;
		this.enquiry = enquiry;
		this.followupMsg = followupMsg;
		this.isActive = isActive;
	}

	//@Id
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY )
	@Column(name = "followup_id", unique = true, nullable = false)
	public int getFollowupId() {
		return this.followupId;
	}

	public void setFollowupId(int followupId) {
		this.followupId = followupId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "staff_id")
	public int getStaff() {
		return this.staff;
	}

	public void setStaff(int staff) {
		this.staff = staff;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "enquiry_id", nullable = false)
	public int getEnquiry() {
		return this.enquiry;
	}

	public void setEnquiry(int enquiry) {
		this.enquiry = enquiry;
	}

	@Column(name = "followup_msg", length = 150)
	public String getFollowupMsg() {
		return this.followupMsg;
	}

	public void setFollowupMsg(String followupMsg) {
		this.followupMsg = followupMsg;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
