package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.google.gson.JsonElement;

/**
 * Paymentmaster generated by hbm2java
 */
@Entity
@Table(name = "paymentmaster", catalog = "computersikho")
public class Paymentmaster implements java.io.Serializable {

	private int paymentMasterId;
	private int course;
	private int student;
	private int courseFees;

	public Paymentmaster() {
	}

	public Paymentmaster(int paymentMasterId, int course, int courseFees) {
		this.paymentMasterId = paymentMasterId;
		this.course = course;
		this.courseFees = courseFees;
	}

	public Paymentmaster(int paymentMasterId, int course, int student, int courseFees) {
		this.paymentMasterId = paymentMasterId;
		this.course = course;
		this.student = student;
		this.courseFees = courseFees;
	}

	@Id

	@Column(name = "payment_master_id", unique = true, nullable = false)
	public int getPaymentMasterId() {
		return this.paymentMasterId;
	}

	public void setPaymentMasterId(int paymentMasterId) {
		this.paymentMasterId = paymentMasterId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "course_id", nullable = false)
	public int getCourse() {
		return this.course;
	}

	public void setCourse(int course) {
		this.course = course;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "student_id")
	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	@Column(name = "course_fees", nullable = false)
	public int getCourseFees() {
		return this.courseFees;
	}

	public void setCourseFees(int courseFees) {
		this.courseFees = courseFees;
	}

}
