package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "computersikho")
public class Payment implements java.io.Serializable {

	private int paymentId;
	private int course;
	private int student;
	private int paymentTypeMaster;
	private Date paymentDate;
	private Boolean paymentDone;
	private Boolean paymentReceiptSend;
	private Integer amount;

	public Payment() {
	}

	public Payment(int paymentId, int course, int student, int paymentTypeMaster) {
		this.paymentId = paymentId;
		this.course = course;
		this.student = student;
		this.paymentTypeMaster = paymentTypeMaster;
	}

	public Payment(int paymentId, int course, int student, int paymentTypeMaster, Date paymentDate,
			Boolean paymentDone, Boolean paymentReceiptSend, Integer amount) {
		this.paymentId = paymentId;
		this.course = course;
		this.student = student;
		this.paymentTypeMaster = paymentTypeMaster;
		this.paymentDate = paymentDate;
		this.paymentDone = paymentDone;
		this.paymentReceiptSend = paymentReceiptSend;
		this.amount = amount;
	}

	@Id

	@Column(name = "payment_id", unique = true, nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "course_id", nullable = false)
	public int getCourse() {
		return this.course;
	}

	public void setCourse(int course) {
		this.course = course;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "student_id", nullable = false)
	public int getStudent() {
		return this.student;
	}

	public void setStudent(int student) {
		this.student = student;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "payment_typeid", nullable = false)
	public int getPaymentTypeMaster() {
		return this.paymentTypeMaster;
	}

	public void setPaymentTypeMaster(int paymentTypeMaster) {
		this.paymentTypeMaster = paymentTypeMaster;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "payment_done")
	public Boolean getPaymentDone() {
		return this.paymentDone;
	}

	public void setPaymentDone(Boolean paymentDone) {
		this.paymentDone = paymentDone;
	}

	@Column(name = "payment_receipt_send")
	public Boolean getPaymentReceiptSend() {
		return this.paymentReceiptSend;
	}

	public void setPaymentReceiptSend(Boolean paymentReceiptSend) {
		this.paymentReceiptSend = paymentReceiptSend;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
