package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "computersikho")
public class Staff implements java.io.Serializable {

	private int staffId;
	private String staffName;
	private String photoUrl;
	private String staffMobile;
	private String staffEmail;
	private String staffUsername;
	private String staffPassword;
	private Set<Followup> followups = new HashSet(0);

	public Staff() {
	}

	public Staff(int staffId, String staffName, String staffEmail, String staffUsername, String staffPassword) {
		this.staffId = staffId;
		this.staffName = staffName;
		this.staffEmail = staffEmail;
		this.staffUsername = staffUsername;
		this.staffPassword = staffPassword;
	}

	public Staff(int staffId, String staffName, String photoUrl, String staffMobile, String staffEmail,
			String staffUsername, String staffPassword, Set<Followup> followups) {
		this.staffId = staffId;
		this.staffName = staffName;
		this.photoUrl = photoUrl;
		this.staffMobile = staffMobile;
		this.staffEmail = staffEmail;
		this.staffUsername = staffUsername;
		this.staffPassword = staffPassword;
		this.followups = followups;
	}

	@Id

	@Column(name = "staff_id", unique = true, nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "staff_name", nullable = false, length = 200)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "photo_url", length = 200)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	@Column(name = "staff_mobile", length = 10)
	public String getStaffMobile() {
		return this.staffMobile;
	}

	public void setStaffMobile(String staffMobile) {
		this.staffMobile = staffMobile;
	}

	@Column(name = "staff_email", nullable = false, length = 50)
	public String getStaffEmail() {
		return this.staffEmail;
	}

	public void setStaffEmail(String staffEmail) {
		this.staffEmail = staffEmail;
	}

	@Column(name = "staff_username", nullable = false, length = 50)
	public String getStaffUsername() {
		return this.staffUsername;
	}

	public void setStaffUsername(String staffUsername) {
		this.staffUsername = staffUsername;
	}

	@Column(name = "staff_password", nullable = false, length = 50)
	public String getStaffPassword() {
		return this.staffPassword;
	}

	public void setStaffPassword(String staffPassword) {
		this.staffPassword = staffPassword;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Followup> getFollowups() {
		return this.followups;
	}

	public void setFollowups(Set<Followup> followups) {
		this.followups = followups;
	}

}
