package com.example.demo.pojos;
// Generated 20 Sep, 2022 5:56:57 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Videos generated by hbm2java
 */
@Entity
@Table(name = "videos", catalog = "computersikho")
public class Videos implements java.io.Serializable {

	private int videoId;
	private int course;
	private String videoDescription;
	private String videoUrl;
	private boolean videoIsActive;
	private Date startDate;
	private Date endDate;

	public Videos() {
	}

	public Videos(int videoId, boolean videoIsActive) {
		this.videoId = videoId;
		this.videoIsActive = videoIsActive;
	}

	public Videos(int videoId, int course, String videoDescription, String videoUrl, boolean videoIsActive,
			Date startDate, Date endDate) {
		this.videoId = videoId;
		this.course = course;
		this.videoDescription = videoDescription;
		this.videoUrl = videoUrl;
		this.videoIsActive = videoIsActive;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id

	@Column(name = "video_id", unique = true, nullable = false)
	public int getVideoId() {
		return this.videoId;
	}

	public void setVideoId(int videoId) {
		this.videoId = videoId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "course_id")
	public int getCourse() {
		return this.course;
	}

	public void setCourse(int course) {
		this.course = course;
	}

	@Column(name = "video_description", length = 65535)
	public String getVideoDescription() {
		return this.videoDescription;
	}

	public void setVideoDescription(String videoDescription) {
		this.videoDescription = videoDescription;
	}

	@Column(name = "video_url", length = 200)
	public String getVideoUrl() {
		return this.videoUrl;
	}

	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	@Column(name = "video_is_active", nullable = false)
	public boolean isVideoIsActive() {
		return this.videoIsActive;
	}

	public void setVideoIsActive(boolean videoIsActive) {
		this.videoIsActive = videoIsActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
